Inprove extract scripts with error checking and 2 args

diff --git a/graphics/extractgfx b/graphics/extractgfx
--- a/graphics/extractgfx
+++ b/graphics/extractgfx
@@ -37,7 +37,32 @@
 # Credit goes to Sander de Jong for information regarding the CHR file format:
 # http://lierohell.free.fr/lierohack/docformats/liero-chr.html
 
-gfxfile="$1"
+usage="Usage: $0 <inputfile.CHR> <outputdir>"
+
+if [ $# != 2 ]; then
+	echo >&2 $usage
+	exit 1
+fi
+
+if [ ! -r "$1" ]; then
+	echo >&2 "Unable to read file '"$1"', aborting"
+	exit 1
+fi
+
+if [ ! -d "$2" ]; then
+	echo >&2 "'"$2"' is not a directory, aborting"
+	exit 1
+fi
+
+if [ ! -w "$2" ]; then
+	echo >&2 "'"$2"' is not writable, aborting"
+	exit 1
+fi
+
+hash convert 2>&- || { echo >&2 "This script requires the "'"convert"'" tool from the "'"ImageMagick"'" suite, aborting"; exit 1; }
+
+inputfile="$1"
+outputdir="$2"
 headersize1=10
 headersize2=4
 headersize3=4
@@ -52,12 +77,13 @@ imgdim1=16x1760
 imgdim2=7x910
 imgdim3=4x120
 
-dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset1" count="$imgsize1" \
+dd if="$inputfile" bs=1 ibs=1 skip="$imgoffset1" count="$imgsize1" \
 	2>/dev/null | \
-	convert -depth 8 -size "$imgdim1" gray:- gfx1.xpm
-dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset2" count="$imgsize2" \
+	convert -depth 8 -size "$imgdim1" gray:- "$outputdir"/gfx1.xpm
+dd if="$inputfile" bs=1 ibs=1 skip="$imgoffset2" count="$imgsize2" \
 	2>/dev/null | \
-	convert -depth 8 -size "$imgdim2" gray:- gfx2.xpm
-dd if="$gfxfile" bs=1 ibs=1 skip="$imgoffset3" count="$imgsize3" \
+	convert -depth 8 -size "$imgdim2" gray:- "$outputdir"/gfx2.xpm
+dd if="$inputfile" bs=1 ibs=1 skip="$imgoffset3" count="$imgsize3" \
 	2>/dev/null | \
-	convert -depth 8 -size "$imgdim3" gray:- gfx3.xpm
+	convert -depth 8 -size "$imgdim3" gray:- "$outputdir"/gfx3.xpm
+
diff --git a/levels/extractlev b/levels/extractlev
--- a/levels/extractlev
+++ b/levels/extractlev
@@ -37,14 +37,26 @@
 # Credit goes to Tim Verweij for information regarding the LEV file format:
 # http://lierohell.free.fr/lierohack/docformats/liero-lev.html
 
-levfilepath="$1"
-levfile="${levfilepath##*/}"
-xpmfile="${levfile%.*}".xpm
+usage="Usage: $0 <inputfile.lev> <outputfile.xpm>"
+
+if [ $# != 2 ]; then
+	echo >&2 $usage
+	exit 1
+fi
+
+if [ ! -r "$1" ]; then
+	echo >&2 "Unable to read file '"$1"', aborting"
+	exit 1
+fi
+
+touch "$2" 2>&- || { echo >&2 "'"$2"' is not writable, aborting"; exit 1; }
+
+inputfile="$1"
+outputfile="$2"
 
 imgsize=$((504 * 350))
 imgdim=504x350
 
-echo $xpmfile
-dd if="$levfilepath" bs=1 ibs=1 count="$imgsize" 2>/dev/null | \
-	convert -depth 8 -size "$imgdim" gray:- "$xpmfile"
+dd if="$inputfile" bs=1 ibs=1 count="$imgsize" 2>/dev/null | \
+	convert -depth 8 -size "$imgdim" gray:- "$outputfile"
 
diff --git a/sounds/extractsounds b/sounds/extractsounds
--- a/sounds/extractsounds
+++ b/sounds/extractsounds
@@ -37,9 +37,9 @@
 # Credit goes to Tim Verweij for information regarding the SND file format:
 # http://lierohell.free.fr/lierohack/docformats/liero-snd.html
 
-usage="Usage: $0 <inputfile>"
+usage="Usage: $0 <inputfile.SND> <outputdir>"
 
-if [ $# != 1 ]; then
+if [ $# != 2 ]; then
 	echo >&2 $usage
 	exit 1
 fi
@@ -49,9 +49,20 @@ if [ ! -r "$1" ]; then
 	exit 1
 fi
 
+if [ ! -d "$2" ]; then
+	echo >&2 "'"$2"' is not a directory, aborting"
+	exit 1
+fi
+
+if [ ! -w "$2" ]; then
+	echo >&2 "'"$2"' is not writable, aborting"
+	exit 1
+fi
+
 hash sox 2>&- || { echo >&2 "This script requires the "'"SoX"'" audio manipulator, aborting"; exit 1; }
 
 sndfile="$1"
+outputdir="$2"
 sounds=30
 headersize=2
 entrysize=16
@@ -87,5 +98,5 @@ for i in $(seq 0 $(($sounds - 1))); do
 		count=$sizesize 2>/dev/null | od -A n -t x4 | tr -d ' ')))"
 
 	dd if=$sndfile ibs=1 skip=$offset count=$size 2>/dev/null | \
-		sox -t raw -b 8 -e signed-integer -r 22050 -B -c 1 - -t wav $name.wav
+		sox -t raw -b 8 -e signed-integer -r 22050 -B -c 1 - -t wav "$outputdir"/"$name".wav
 done
