packsounds: touch before write-testing

diff --git a/debian/scripts/packsounds b/debian/scripts/packsounds
--- a/debian/scripts/packsounds
+++ b/debian/scripts/packsounds
@@ -41,6 +41,7 @@ if [ $# != 1 ]; then
 	exit 1
 fi
 
+touch "$1" || { echo >&2 "Unable to write to file '"$1"', aborting"; exit 1; }
 if [ ! -w "$1" ]; then
 	echo >&2 "Unable to write to file '"$1"', aborting"
 	exit 1
